CREATE SEQUENCE HIBERNATE_SEQUENCE INCREMENT 1 START 1 MINVALUE 0;

/* KORISNIK  -> KORISNIK_ZAPOSLENIK <- APLIKACIJA 
	     -> KORISNIK_KLIJENT <- KLIJENT -> APLIKACIJA -> PRIJAVA -> INTERVENCIJA <- KORISNIK_ZAPOSLENIK

    PRIJAVA <- KORISNIK_KLIJENT	

    APLIKACIJA
        - ID
        - SIFRA
        - NAZIV

    KLIJENT
        - ID
        - SIFRA
        - NAZIV		

    KORISNIK
	- ID
	- IME
	- PREZIME
	- EMAIL
	- KORISNICKO_IME
	- LOZINKA

     KORISNIK_ZAPOSLENIK
        - ID
        - KORISNIK_ID
        - APLIKACIJA_ID

     KORISNIK_KLIJENT  
	- ID
	- KORISNIK_ID
	- KLIJENT_ID	

     PRIJAVA
        - ID
        - RBR ???
        - DATUM_ZAPRIMANJA (datum unosa)
        - DATUM_POCETKA_RJESAVANJA (datum i vrijeme kad je unesen KORISNIK_ZAPOSLENIK_ID)
        - APLIKACIJA_ID (aplikacija na koju se odnosi prijava)
        - KORISNIK_KLIJENT_ID (korisnik koji je podnio prijavu)
        - KORISNIK_ZAPOSLENIK_ID (zaposlenik koji je preuzeo prijavu na riješavanje)		
        - STATUS (RJEŠENO|RJEŠAVANJE U TIJEKU|NERIJEŠENO) (kod unosa je status: neriješeno, kod upisa KORISNIK_ZAPOSLENIK_ID status se mijenja u RJEŠAVANJE U TIJEKU, ručno se označava da je RIJEŠENO)

     INTERVENCIJA
	- ID
	- PRIJAVA_ID
	- KORISNIK_ZAPOSLENIK_ID
	- OPIS	
	- TRAJANJE (MINUTE)
        						
					
*/

CREATE TABLE APLIKACIJA (
  ID INT NOT NULL DEFAULT nextval('HIBERNATE_SEQUENCE') PRIMARY KEY,
  SIFRA VARCHAR(10) NOT NULL,
  NAZIV VARCHAR(20) NOT NULL);

CREATE UNIQUE INDEX APLIKACIJA_UK ON APLIKACIJA(SIFRA); 

CREATE TABLE KLIJENT (
  ID INT NOT NULL DEFAULT nextval('HIBERNATE_SEQUENCE') PRIMARY KEY,
  SIFRA VARCHAR(10) NOT NULL,
  NAZIV VARCHAR(20) NOT NULL);

CREATE UNIQUE INDEX KLIJENT_UK ON KLIJENT(SIFRA); 

CREATE TABLE KORISNIK (
  ID INT NOT NULL DEFAULT nextval('HIBERNATE_SEQUENCE') PRIMARY KEY,
  IME VARCHAR(20) NOT NULL,
  PREZIME VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(80) NOT NULL,
  LOZINKA VARCHAR(40) NOT NULL);

CREATE UNIQUE INDEX KORISNIK_UK ON KORISNIK(EMAIL); 

CREATE TABLE KORISNIK_ZAPOSLENIK (
  ID INT NOT NULL DEFAULT nextval('HIBERNATE_SEQUENCE') PRIMARY KEY,
  KORISNIK_ID INT NOT NULL,
  APLIKACIJA_ID INT NOT NULL,
  CONSTRAINT KOR_ZAP_KOR_FK FOREIGN KEY (KORISNIK_ID) REFERENCES KORISNIK (ID),
  CONSTRAINT KOR_ZAP_APL_FK FOREIGN KEY (APLIKACIJA_ID) REFERENCES APLIKACIJA (ID));

CREATE UNIQUE INDEX KORISNIK_ZAPOSLENIK_UK  ON KORISNIK_ZAPOSLENIK(KORISNIK_ID, APLIKACIJA_ID);

CREATE TABLE KORISNIK_KLIJENT (
  ID INT NOT NULL DEFAULT nextval('HIBERNATE_SEQUENCE') PRIMARY KEY,
  KORISNIK_ID INT NOT NULL,
  KLIJENT_ID INT NOT NULL,
  CONSTRAINT KOR_KLI_KOR_FK FOREIGN KEY (KORISNIK_ID) REFERENCES KORISNIK (ID),
  CONSTRAINT KOR_KLI_KLI_FK FOREIGN KEY (KLIJENT_ID) REFERENCES KLIJENT (ID));

CREATE UNIQUE INDEX KORISNIK_KLIJENT_UK  ON KORISNIK_KLIJENT(KORISNIK_ID, KLIJENT_ID);